In [1]:
%pylab
import numpy as np
import pandas as pd

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


In [3]:
train_data = pd.read_csv("data/train_data.csv")
train_matrix = pd.pivot_table(train_data, values='quantity', 
                              index=['customer_id'], 
                              columns=['item_id'],
                             aggfunc=np.sum,
                             fill_value=0)   #change train from dataframe to matrix form
# row is customer, column is item and then the value is aggregated sum of quantity
train_matrix.shape

(4889, 3365)

In [4]:
R = train_matrix.values

In [7]:
popularity = np.sum(R, axis=0)  # axis=0 means sum over column

In [11]:
np.argsort(popularity)[::-1]

array([1392, 1201, 1458, ..., 1822, 1823, 1682])

In [17]:
np.unique(popularity, return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35,
        36, 37, 41, 43, 44, 49, 50, 58, 63]),
 array([1251,  630,  354,  251,  134,  115,   86,   65,   71,   63,   41,
          35,   35,   36,   25,   21,   18,   19,    6,   13,   16,    8,
           7,    5,    3,    7,    4,   10,    3,    3,    3,    5,    5,
           3,    2,    3,    1,    1,    2,    1,    2,    1,    1]))

In [18]:
train_matrix.shape

(4889, 3365)

In [22]:
np.savetxt("data/R.csv", R, delimiter=",")

In [25]:
R_tild = np.loadtxt("data/R.csv", delimiter=",")

In [27]:
np.unique(R_tile == R)

array([ True], dtype=bool)